FROM alpine as build-env-base

RUN apk add --no-cache build-base git cmake

# compile wsserver
WORKDIR /tmp/
RUN git clone https://github.com/Theldus/wsServer
WORKDIR /tmp/wsServer
RUN make
RUN make install

# compiles json-c
WORKDIR /tmp/
RUN git clone https://github.com/json-c/json-c.git
WORKDIR /tmp/json-c-build
RUN mkdir build
RUN cmake ../json-c  
RUN make
RUN make install
RUN ls -ltra /usr/local/lib

# compile application
FROM build-env-base as build-env

# compile server
WORKDIR /app
COPY ../src /app/src
COPY ../makefile /app/makefile
RUN make

# generate final container
FROM alpine as sfserver
#RUN rm /tmp/* -Rf
#RUN rm /app/src/* -Rf
RUN apk add --no-cache json-c

COPY --from=build-env /app/build/sfbus-server /app/sfbus-server
#COPY --from=build-env /usr/lib/libjson-c.so.5 /usr/lib/libjson-c.so.5
COPY --from=build-env /usr/local/lib64/libws.a /usr/local/lib64/libws.a

EXPOSE 8089
CMD ["/app/sfbus-server","-c","/app/config.json","-p","/dev/ttyUSB0"]
